import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>CICLO DE VIDA | Instituto Mexicano del Cemento y del Concreto A.C.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CICLO DE VIDA
        </h1>

        <p className={styles.description}>
          INSTITUTO MEXICANO DEL CEMENTO Y DEL CONCRETO A.C.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://imcyc.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          © 2022 Todos Los Derechos Reservados. Instituto Mexicano del Cemento y del Concreto A.C.
        </a>
      </footer>
    </div>
  )
}
