import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Button from '@mui/material/Button';

export default function Layout({ children }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>CALCULADORA DEL CICLO DE VIDA DEL CONCRETO | Instituto Mexicano del Cemento y del Concreto A.C.</title>
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" />
            </Head>

            {children}

            <footer className={styles.footer}>
                <a
                    href="https://imcyc.com"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    © 2022 Todos Los Derechos Reservados. Instituto Mexicano del Cemento y del Concreto A.C.
                </a>
            </footer>
        </div>
    )
}
